### ISSUE TITLE
Website Roadmap 

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#207]
Design prototype: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/

Presented, roughly, as a linear priority list, but in reality quite a lot are interlinked and so can be worked on concurrently.

**Comment by daltonfury42** [comment]
**Home Page**

![image](https://user-images.githubusercontent.com/11256376/92302059-9ef90f00-ef86-11ea-90a3-fdf7e5767f49.png)

* [ ]  Home page - Without the navbar (https://github.com/SimplQ/simplQ-frontend/issues/208)

**Comment by sajmalyousef** [comment]
**Admin Page**
![image](https://user-images.githubusercontent.com/13188906/93702523-da720c80-fb34-11ea-8bf4-da2e0a771e21.png)

- [ ] Skeleton (basic design of the page)
- [ ] Styling navbar 
- [ ]  Modify share button (https://github.com/SimplQ/simplQ-frontend/issues/223)
- [ ] Styling Header section
- [ ] Add manually 
- [ ] Token
- [ ] Resume/pause
- [ ] Delete
- [ ] Warning ribbon

**Comment by sajmalyousef** [comment]
![image](https://user-images.githubusercontent.com/13188906/95236597-c57bc580-0824-11eb-9cf9-7ccc6135a8b9.png)

Join Queue Page

**Comment by sajmalyousef** [comment]
![image](https://user-images.githubusercontent.com/13188906/95237472-e4c72280-0825-11eb-812e-5b921edad488.png)
**Queue Status Page**

[Desing Link](https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/e87838cd-febc-4f37-a68a-9daa0d6b207b/?fullscreen)
